"""Add Conversation and ConversationPart models

Revision ID: f9fb3e81ba80
Revises: ab5233220cb2
Create Date: 2025-07-02 13:32:57.722185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fb3e81ba80'
down_revision: Union[str, Sequence[str], None] = 'ab5233220cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corpus_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_corpus_id'), 'conversations', ['corpus_id'], unique=False)
    op.create_table('conversation_parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('context_chunks', sa.JSON(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('embedding_model_used', sa.String(length=100), nullable=False),
    sa.Column('completion_model_used', sa.String(length=100), nullable=False),
    sa.Column('chunks_retrieved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_parts_conversation_id'), 'conversation_parts', ['conversation_id'], unique=False)
    # Removed constraint operations for corpus_files
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed constraint operations for corpus_files
    op.drop_index(op.f('ix_conversation_parts_conversation_id'), table_name='conversation_parts')
    op.drop_table('conversation_parts')
    op.drop_index(op.f('ix_conversations_corpus_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
